#configuration for creating the database and table
default_db: "postgres" #the default postgresql database
host: "localhost" #the host of the database
new_db: "test" #the name of the new database that will be created


#configuration for creating the table. For more columns, copy/paste 'name' and 'type'.
table:
  name: "test_table" #the name of the table
  audit_columns: #the names of the audit columns
    - name: "key" #audit column
      type: "text" #audit column
    - name: "inserted_dttm" #audit column
      type: "timestamp without time zone" #audit column
    - name: "deleted_dttm" #audit column
      type: "timestamp without time zone" #audit column
  columns:
    - name: "firstname" #column name
      type: "text" #data type
    - name: "lastname"
      type: "text"
